### PR TITLE
add header background on scroll body overlap

### PR DESCRIPTION
**Pull request by justindomingue**
using @react-hook/window-scroll to avoid performance hits and readability

### CODE REVIEW

**Comment by justindomingue** [comment]
Screen Shot 2021-05-12 at 11 16 53 AM

**Comment by moodysalem** [comment]
hmmmmm what about sliding it out of the way?

**Comment by justindomingue** [comment]
> hmmmmm what about sliding it out of the way?

@moodysalem, @callil mentioned it, much better!

**Comment by justindomingue** [comment]
fixes #1498

**Pull request merged**
