### PR TITLE
Ask user to fill in reproduction steps in GitHub issue on page crash.

### PR DESCRIPTION
**Pull request by jochenboesmans**
Hopefully users will actually fill it in.

It also might be useful to look into giving some major components a displayName in order to make the stacktraces a bit more useful in production's minified js as it's currently quite difficult to understand what's going on from the stacktrace alone.

### CODE REVIEW

**Comment by moodysalem** [comment]
we could also include the redux store and current URL but i'm hesitant to include the store since it will have transactions they sent (even if they r submitting it). can include a slice of the store maybe

**Comment by moodysalem** [comment]
the error name in the issue title would be a big improvement for marking duplicates

**Comment by moodysalem** [comment]
also should link to support!

**Comment by moodysalem** [comment]
cleaned it up a bit

**Comment by web3devsa** [comment]
apple.com

**Pull request closed without merging**
