### PR TITLE
Update uniswap-default.tokenlist.json

### PR DESCRIPTION
**Pull request by admazzola**
Adding 0xBTC, open source PoW mineable token

### CODE REVIEW

**Comment by admazzola** [comment]
Proof of activity, please see transactions: 

https://etherscan.io/address/0xb6ed7644c69416d67b522e20bc294a9a9b405b31

Please see active PoW hashrate: 

https://0x1d00ffff.github.io/0xBTC-Stats/?page=stats&

If you need more info for this matter you can reach me from this github account

**Comment by moodysalem** [comment]
very outdated, no longer relevant to this repo

**Comment by admazzola** [comment]
Sorry what is outdated ?

**Comment by moodysalem** [comment]
> Sorry what is outdated ?

my bad, all token list requests should go to the default token list repo, i was unaware that this token list was added back to the interface repo and thought it was old and getting bumped.

**Pull request closed without merging**
