### PR TITLE
Add card explaining risk of impermanent loss for LP (#1122)

### PR DESCRIPTION
**Pull request by jochenboesmans**
Screenshot 2020-09-28 at 13 31 28

### CODE REVIEW

**Comment by callil** [comment]
@jochenboesmans I personally prefer to keep a single card in the view as demonstrated here: #1138 

I do like your copy though - it's more direct. Maybe there is a way to merge the design from @AshishGapat and the copy here?

**Comment by jochenboesmans** [comment]
@callil 

The main reason for putting this in a separate card was that most of the card would be black with the additional text. Happy for the other PR to be merged instead though.

**Comment by AshishGapat** [comment]
@jochenboesmans 

I like your copy better too. How do we go about this merge? I just got started with OSS so correct me if I'm wrong, but maybe you can make a pull request to my fork?

**Comment by jochenboesmans** [comment]
> @jochenboesmans
> 
> I like your copy better too. How do we go about this merge? I just got started with OSS so correct me if I'm wrong, but maybe you can make a pull request to my fork?

Feel free to just add a commit to your branch, might be easier.

**Pull request closed without merging**
