### PR TITLE
improvement(routing): use WBTC pairs for routing swaps

### PR DESCRIPTION
**Pull request by thegismar**
Just added WBTC as one of the options to route in the UI after getting the OK from callil in Discord

### CODE REVIEW

**Comment by callil** [comment]
Thanks @thegismar - FWIW here's a previous discussion around this: https://github.com/Uniswap/uniswap-interface/pull/1060

**Comment by thegismar** [comment]
> Thanks @thegismar - FWIW here's a previous discussion around this: #1060

Oh yeah.. The ask there is a bit different though.. Thanks for already looking at this!! That made a lot of people happy.

**Comment by sksksksksksksk** [comment]
Looks like there's an issue with one of your tests? Not sure why this didn't get merged already, or why the linter check is failing... says something about not being able to force update?

https://github.com/Uniswap/uniswap-interface/pull/1241/checks?check_run_id=1584900217

**Comment by thegismar** [comment]
> Looks like there's an issue with one of your tests? Not sure why this didn't get merged already, or why the linter check is failing... says something about not being able to force update?
> 
> https://github.com/Uniswap/uniswap-interface/pull/1241/checks?check_run_id=1584900217

please fix it fix it fix it fix it ;-)

**Comment by sksksksksksksk** [comment]
> > Looks like there's an issue with one of your tests? Not sure why this didn't get merged already, or why the linter check is failing... says something about not being able to force update?
> > https://github.com/Uniswap/uniswap-interface/pull/1241/checks?check_run_id=1584900217
> 
> please fix it fix it fix it fix it ;-)

Create a new branch in your uniswap-interface fork, resubmit the pull request with that branch. This [b]should[b] resolve the error.

**Comment by ianlapham** [comment]
- merged in #1269 , just added some styles on top of your change

**Pull request closed without merging**
