### PR TITLE
Add Hebrew translation

### PR DESCRIPTION
**Pull request by ramiy**
Add translation file for Hebrew.

### CODE REVIEW

**Comment by ramiy** [comment]
Any update?

**Comment by moodysalem** [comment]
> Any update?

Our use of the i18n library in the interface is greatly lacking, and fixing that will obsolete a lot of this work, but we will soon prioritize it. 

In addition, I can't check the translations, which makes it harder to merge this.

**Comment by ramiy** [comment]
@moodysalem You can use google translate to check some strings.

Any way, when you implement the Hebrew translation, I also want to contribute to front-end to fix RTL issues. But I need to see the site in Hebrew.

In any case, I'm want to contribute to the project.

**Comment by justindomingue** [comment]
Hey @ramiy I'm currently going over our i18n process to 1) cover all strings inside Uniswap and 2) make it simpler for community members to contribute. Sorry abotu the delay on the Hebrew translation. I'll ping this thread again where the PR is merged. #1692 Would appreciate your help in translating the new strings as well once it's ready!

**Comment by justindomingue** [comment]
@ramiy I wrote a quick start doc: [CONTRIBUTING.md](https://github.com/Uniswap/uniswap-interface/blob/main/CONTRIBUTING.md)

You'll need to add the new locale for Hebrew and then copy over the strings you have in this CL but some of them may be deprecated.

Should be able to reuse these at least
* pool
* swap
* swapAnyway
* addLiquidity
* removeLiquidity

**Comment by justindomingue** [comment]
@ramiy We've moved our translation workflow to [Crowdin](https://crowdin.com/project/uniswap-interface)! It will be much easier to manage! Would appreciate your help in translating Hebrew on the platform. Closing this PR.

**Pull request closed without merging**
