### PR TITLE
Rewrite paths as absolute

### PR DESCRIPTION
**Pull request by anxolin**
This PR is related to #1184 Issue.

## Context
This PR simplifies the imports by using absolute paths. It's the seconds part of this PR ( #1185) where it was added the support for absolute paths.

For context https://create-react-app.dev/docs/importing-a-component

## Some notes
* Although this PR is big, it **ONLY** modifies the routes that refer to a directory hanging directly from `src`. It doesn't do any other change in the code base.
* It was modified using a REGEX, following the pattern `import '(..\/)+(components|assets|<all other dirs>)\/` 
* These are the dirs used in the REGEX:
image
* There's one exception. The constants cannot be resolved using `import { ... } from 'constants'`, so they were changed into `import { ... } from 'constants/index'`

## Not included in this PR
Although this REGEX manages to change a big part of the imports, I decided against "going manual" and modify some relative imports like: 

```ts
import CurrencySearchModal from '../SearchModal/CurrencySearchModal'
```

This is more error prone, so they can be done in a separated PR, getting the ones changed in this PR out of the way.

### CODE REVIEW

**Review by TomasFlow — APPROVED** [review]

**Comment by anxolin** [comment]
Any chance this can be also merged @moodysalem?

**Comment by moodysalem** [comment]
> Any chance this can be also merged @moodysalem?

Yup sorry will take a look. It's just a lot of work to manually review so it would be easier if I just copied your approach and applied it to master

**Comment by anxolin** [comment]
I understand. Whatever is easier for u, yes there's a lot of changes and not fun to review, but I think the way Github highlight the change is not that bad. You'll just see a lot of `../..` disappearing and the project working as before 😃

**Comment by anxolin** [comment]
Hei @moodysalem did you have a chance to review the changes. I saw there was conflicts with master, and I solved them, but it would be nice if we review it sooner, so it doesn't diverge from master (there's a lot of small changes, so it will keep happening)

**Comment by moodysalem** [comment]
I hear you but I'm worried about merging this and missing something that breaks the interface or worse and don't think it's worth the due diligence to review since it has no impact on the end user xp and minimal impact on the developer xp. If you want to get this changed across the codebase, I would be more comfortable with a PR adding a bash script that rewrites all the paths, which I can more easily review and then apply to master

**Comment by anxolin** [comment]
@moodysalem , yes I totally get it. I provided some instructions here, I hope with this makes things easier https://github.com/Uniswap/uniswap-interface/issues/1207

**Pull request closed without merging**
